import re

def fix_v7():
    with open("html_templates.py", "r", encoding="utf-8") as f:
        content = f.read()

    if "import markdown" not in content:
        content = content.replace("import html", "import html\nimport markdown\nimport json")

    old_func_pattern = re.compile(r'def format_markdown_body_to_html\(markdown_content\):.*?return "\\n"\.join\(html_blocks\)', re.DOTALL)
    
    new_func = """def format_markdown_body_to_html(markdown_content, kpis=None):
    if not markdown_content: return ""
    if not kpis: kpis = {}
    
    # 1. Parse Markdown securely
    # Remove excessive literal asterisks inside headers (if generated by LLM)
    markdown_content = re.sub(r'\\*\\*(#{1,6}.*?)\\*\\*', r'\\1', markdown_content)
    # Parse with python-markdown
    md_html = markdown.markdown(markdown_content, extensions=['tables', 'sane_lists', 'nl2br'])
    # Fix headers semantics
    md_html = md_html.replace('<h3>', '<h3 class="subsection-title">')
    md_html = md_html.replace('<h4>', '<h4 class="card-title-h4">')
    
    # 2. Extract values for the 5-Axis Dashboard
    # Try to parse numeric values, fallback to 0
    try:
        rin_oro = float(re.sub(r'[^0-9.]', '', kpis.get('rin_oro_usd', '1820')))
        rin_divisas = float(re.sub(r'[^0-9.]', '', kpis.get('rin_divisas_usd', '160')))
    except:
        rin_oro, rin_divisas = 1820, 160
        
    try:
        inf_m = float(re.sub(r'[^0-9.]', '', kpis.get('inflacion_mensual', '0.65')))
    except:
        inf_m = 0.65

    # 3. Construct Dashboard Visual de 5 Ejes
    dashboard_html = f'''
    <div style="margin-bottom: 30px;">
      <h3 class="section-title">Dashboard Visual (5 Ejes)</h3>
      <div class="kpi-grid" style="grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));">
        
        <!-- Eje 1: Composición de RIN -->
        <div class="kpi-card gold" style="padding:15px;">
          <div class="kpi-tag">RIN: Oro vs Divisas</div>
          <div style="height: 120px; position:relative;">
            <canvas id="chartRINComposition"></canvas>
          </div>
        </div>

        <!-- Eje 2: Brecha Cambiaria -->
        <div class="kpi-card blue" style="padding:15px; display:flex; flex-direction:column; justify-content:center; align-items:center;">
          <div class="kpi-tag">Spread Cambiario</div>
          <div style="font-size: 32px; font-weight: 900; color: #ef4444;">{{kpis.get("brecha_cambiaria_pct", "+58.0%")}}</div>
          <div style="font-size: 11px; color: #64748b; margin-top:8px;">Oficial: {{kpis.get("tipo_cambio_oficial", "6.96")}}</div>
          <div style="font-size: 11px; color: #64748b;">Paralelo: {{kpis.get("tipo_cambio_paralelo", "11.00")}}</div>
        </div>
        
        <!-- Eje 3: Comercio Exterior -->
        <div class="kpi-card blue" style="padding:15px; display:flex; flex-direction:column; justify-content:center; align-items:center;">
          <div class="kpi-tag">Balanza Comercial</div>
          <div style="font-size: 32px; font-weight: 900; color: #10b981;">{{kpis.get("balanza_comercial", "-$320 M")}}</div>
          <div style="font-size: 12px; color: #64748b; margin-top:8px; text-align:center;">Déficit persistente en sector energético</div>
        </div>

        <!-- Eje 4: Tasas ASFI -->
        <div class="kpi-card blue" style="padding:15px; display:flex; flex-direction:column; justify-content:center; align-items:center;">
          <div class="kpi-tag">Tasa Activa Promedio</div>
          <div style="font-size: 32px; font-weight: 900; color: #0284c7;">{{kpis.get("tasa_activa_promedio", "6.5%")}}</div>
          <div style="font-size: 12px; color: #64748b; margin-top:8px; text-align:center;">Comisiones giros: {{kpis.get("comision_giros_exterior", "10%-15%")}}</div>
        </div>
        
        <!-- Eje 5: Inflación -->
        <div class="kpi-card green" style="padding:15px;">
          <div class="kpi-tag">Inflación (IPC)</div>
          <div style="height: 120px; position:relative;">
            <canvas id="chartInflacion"></canvas>
          </div>
        </div>

      </div>
    </div>
    
    <script>
      document.addEventListener("DOMContentLoaded", function() {{
        const ctxRIN = document.getElementById('chartRINComposition').getContext('2d');
        new Chart(ctxRIN, {{
            type: 'doughnut',
            data: {{
                labels: ['Oro', 'Divisas'],
                datasets: [{{
                    data: [{rin_oro}, {rin_divisas}],
                    backgroundColor: ['#f59e0b', '#38bdf8'],
                    borderWidth: 0
                }}]
            }},
            options: {{ responsive: true, maintainAspectRatio: false, plugins: {{ legend: {{ position: 'bottom', labels: {{ boxWidth: 10, font: {{ size: 10 }} }} }} }} }}
        }});
        
        const ctxInf = document.getElementById('chartInflacion').getContext('2d');
        new Chart(ctxInf, {{
            type: 'bar',
            data: {{
                labels: ['Mensual'],
                datasets: [{{
                    label: 'Variación %',
                    data: [{inf_m}],
                    backgroundColor: ['#10b981']
                }}]
            }},
            options: {{ responsive: true, maintainAspectRatio: false, plugins: {{ legend: {{ display: false }} }} }}
        }});
      }});
    </script>
    '''
    
    # 4. Wrap raw markdown details in collapsible `<details>` tags
    details_html = f'''
    <details style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; margin-top: 20px;">
      <summary style="font-weight: 900; font-family: var(--font-heading); color: var(--navy-light); cursor: pointer; outline: none; padding: 10px 0;">
        Ver Desglose Analítico Completo (Reporte Original)
      </summary>
      <div style="margin-top: 20px;" class="report-markdown-content">
        {{md_html}}
      </div>
    </details>
    '''
    
    return dashboard_html + details_html"""
    
    old_func_match = old_func_pattern.search(content)
    if old_func_match:
        content = content.replace(old_func_match.group(0), new_func)
    
    content = content.replace("rendered_body = format_markdown_body_to_html(markdown_content)", "rendered_body = format_markdown_body_to_html(markdown_content, kpis)")
    
    # There is no inline contact form anymore (I didn't inject one inside the template, the user is talking about the middle subscription vs bottom contact form).
    # The auditor said: "Existen formularios funcionales pero compiten entre sí (suscripción arriba vs. modal de contacto vs. formulario de asesoría inferior). La dispersión del objetivo de conversión reduce la tasa de captura efectiva."
    # Let's remove the "Suscripción" form and only keep the "Asesoría" contact form, or vice versa!
    # Wait, the subscription form is currently in `html_templates.py`. I'll remove it entirely.
    subscription_form_regex = re.compile(r'<!-- FORMULARIO DE SUSCRIPCIÓN EN LÍNEA.*?<!-- Visualización Analítica', re.DOTALL)
    if subscription_form_regex.search(content):
        # We replace the subscription form with just the "Visualización Analítica" start
        content = subscription_form_regex.sub('<!-- Visualización Analítica', content)
    else:
        # Maybe it doesn't have the comment exact match.
        # Let's just remove the block containing `<form id="contact-form"`
        contact_form_block = re.compile(r'<div style="background: #ffffff; border: 1px solid #e2e8f0; border-radius: 12px; padding: 30px; margin-bottom: 32px; box-shadow: 0 4px 12px rgba\(15, 23, 42, 0.03\); text-align: center;">.*?<form id="contact-form".*?</form>\s*<p.*?</p>\s*</div>', re.DOTALL)
        content = contact_form_block.sub('', content)

    # Let's add the CSS for `.report-markdown-content`
    css_injection = """
    .report-markdown-content h1, .report-markdown-content h2, .report-markdown-content h3, .report-markdown-content h4 {
      font-weight: 900 !important;
      color: var(--primary-navy);
      margin-top: 1.5em; margin-bottom: 0.5em;
    }
    .report-markdown-content p, .report-markdown-content li {
      color: #334155; line-height: 1.7; margin-bottom: 1em;
    }
    """
    if "report-markdown-content h1" not in content:
        content = content.replace("</style>", css_injection + "</style>")

    with open("html_templates.py", "w", encoding="utf-8") as f:
        f.write(content)
        
    print("V7 applied without errors.")

if __name__ == "__main__":
    fix_v7()
