import json
import re
import html
import markdown
import json

def get_risk_colors(risk_level):
    level = str(risk_level).lower()
    if "crit" in level or "rojo" in level or "red" in level:
        return {
            "bg": "#fef2f2",
            "border": "#ef4444",
            "text": "#991b1b",
            "badge_bg": "#dc2626",
            "badge_text": "#ffffff",
            "icon": "🔴",
            "label": "RIESGO CRÍTICO"
        }
    elif "alt" in level or "amber" in level or "amar" in level:
        return {
            "bg": "#fffbeb",
            "border": "#f59e0b",
            "text": "#92400e",
            "badge_bg": "#d97706",
            "badge_text": "#ffffff",
            "icon": "🟡",
            "label": "RIESGO ALTO"
        }
    else:
        return {
            "bg": "#f0fdf4",
            "border": "#22c55e",
            "text": "#166534",
            "badge_bg": "#16a34a",
            "badge_text": "#ffffff",
            "icon": "🟢",
            "label": "RIESGO MODERADO"
        }

def format_markdown_body_to_html(markdown_content, kpis=None):
    if not markdown_content: return ""
    if not kpis: kpis = {}
    
    # 1. Parse Markdown securely
    # Remove excessive literal asterisks inside headers (if generated by LLM)
    markdown_content = re.sub(r'\*\*(#{1,6}.*?)\*\*', r'\1', markdown_content)
    # Parse with python-markdown
    md_html = markdown.markdown(markdown_content, extensions=['tables', 'sane_lists', 'nl2br'])
    # Fix headers semantics
    md_html = md_html.replace('<h3>', '<h3 class="subsection-title">')
    md_html = md_html.replace('<h4>', '<h4 class="card-title-h4">')
    
    # 2. Extract values for the 5-Axis Dashboard
    # Try to parse numeric values, fallback to 0
    try:
        rin_oro = float(re.sub(r'[^0-9.]', '', kpis.get('rin_oro_usd', '1820')))
        rin_divisas = float(re.sub(r'[^0-9.]', '', kpis.get('rin_divisas_usd', '160')))
    except:
        rin_oro, rin_divisas = 1820, 160
        
    try:
        inf_m = float(re.sub(r'[^0-9.]', '', kpis.get('inflacion_mensual', '0.65')))
    except:
        inf_m = 0.65

    # 3. Construct Dashboard Visual de 5 Ejes
    dashboard_html = f'''
    <div style="margin-bottom: 30px;">
      <h3 class="section-title">Dashboard Visual (5 Ejes)</h3>
      <div class="kpi-grid" style="grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));">
        
        <!-- Eje 1: Composición de RIN -->
        <div class="kpi-card gold" style="padding:15px;">
          <div class="kpi-tag">RIN: Oro vs Divisas</div>
          <div style="height: 120px; position:relative;">
            <canvas id="chartRINComposition"></canvas>
          </div>
        </div>

        <!-- Eje 2: Brecha Cambiaria -->
        <div class="kpi-card blue" style="padding:15px; display:flex; flex-direction:column; justify-content:center; align-items:center;">
          <div class="kpi-tag">Spread Cambiario</div>
          <div style="font-size: 32px; font-weight: 900; color: #ef4444;">{kpis.get("brecha_cambiaria_pct", "+58.0%")}</div>
          <div style="font-size: 11px; color: #64748b; margin-top:8px;">Oficial: {kpis.get("tipo_cambio_oficial", "6.96")}</div>
          <div style="font-size: 11px; color: #64748b;">Paralelo: {kpis.get("tipo_cambio_paralelo", "11.00")}</div>
        </div>
        
        <!-- Eje 3: Comercio Exterior -->
        <div class="kpi-card blue" style="padding:15px; display:flex; flex-direction:column; justify-content:center; align-items:center;">
          <div class="kpi-tag">Balanza Comercial</div>
          <div style="font-size: 32px; font-weight: 900; color: #10b981;">{kpis.get("balanza_comercial", "-$320 M")}</div>
          <div style="font-size: 12px; color: #64748b; margin-top:8px; text-align:center;">Déficit persistente en sector energético</div>
        </div>

        <!-- Eje 4: Tasas ASFI -->
        <div class="kpi-card blue" style="padding:15px; display:flex; flex-direction:column; justify-content:center; align-items:center;">
          <div class="kpi-tag">Tasa Activa Promedio</div>
          <div style="font-size: 32px; font-weight: 900; color: #0284c7;">{kpis.get("tasa_activa_promedio", "6.5%")}</div>
          <div style="font-size: 12px; color: #64748b; margin-top:8px; text-align:center;">Comisiones giros: {kpis.get("comision_giros_exterior", "10%-15%")}</div>
        </div>
        
        <!-- Eje 5: Inflación -->
        <div class="kpi-card green" style="padding:15px;">
          <div class="kpi-tag">Inflación (IPC)</div>
          <div style="height: 120px; position:relative;">
            <canvas id="chartInflacion"></canvas>
          </div>
        </div>

      </div>
    </div>
    
    <script>
      document.addEventListener("DOMContentLoaded", function() {{
        const ctxRIN = document.getElementById('chartRINComposition').getContext('2d');
        new Chart(ctxRIN, {{
            type: 'doughnut',
            data: {{
                labels: ['Oro', 'Divisas'],
                datasets: [{{
                    data: [{rin_oro}, {rin_divisas}],
                    backgroundColor: ['#f59e0b', '#38bdf8'],
                    borderWidth: 0
                }}]
            }},
            options: {{ responsive: true, maintainAspectRatio: false, plugins: {{ legend: {{ position: 'bottom', labels: {{ boxWidth: 10, font: {{ size: 10 }} }} }} }} }}
        }});
        
        const ctxInf = document.getElementById('chartInflacion').getContext('2d');
        new Chart(ctxInf, {{
            type: 'bar',
            data: {{
                labels: ['Mensual'],
                datasets: [{{
                    label: 'Variación %',
                    data: [{inf_m}],
                    backgroundColor: ['#10b981']
                }}]
            }},
            options: {{ responsive: true, maintainAspectRatio: false, plugins: {{ legend: {{ display: false }} }} }}
        }});
      }});
    </script>
    '''
    
    # 4. Wrap raw markdown details in collapsible `<details>` tags
    details_html = f'''
    <details class="analytics-accordion" style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; margin-top: 20px; transition: all 0.3s ease;">
      <summary style="font-weight: 900; font-family: var(--font-heading); color: var(--navy-light); cursor: pointer; outline: none; padding: 10px 0;">
        <span>Ver Desglose Analítico Completo (Reporte Original)</span>
      </summary>
      <div style="margin-top: 20px;" class="report-markdown-content">
        {md_html}
      </div>
    </details>
    '''
    
    return dashboard_html + details_html

def generate_email_hook_html(data, web_report_url, recipient_email="Cliente"):
    """
    Genera la plantilla de correo electrónico optimizada (El Gancho)
    con CSS Inline 100% compatible con clientes de correo móviles y de escritorio.
    """
    fecha = data.get("fecha", "")
    preheader = data.get("preheader", "Resumen Ejecutivo de Macroeconomía Boliviana.")
    riesgo = data.get("riesgo_general", {})
    nivel_riesgo = riesgo.get("nivel", "Alto")
    colors = get_risk_colors(nivel_riesgo)
    alerta_principal = riesgo.get("alerta_principal", "")
    accion_recomendada = riesgo.get("accion_recomendada", "")
    
    kpis = data.get("kpis", {})
    tc_oficial = kpis.get("tipo_cambio_oficial", "6.86 / 6.96")
    tc_paralelo = kpis.get("tipo_cambio_paralelo", "11.00 BOB/USDT")
    
    bloques = data.get("bloques_resumidos", {})
    rin_txt = bloques.get("rin_divisas", "RIN estables concentradas en oro.")
    comercio_txt = bloques.get("comercio_exterior", "Déficit comercial persistente.")
    banca_txt = bloques.get("inflacion_banca", "Inflación con presión en importados.")

    # URL base para activos (usando el web_report_url si viene limpio, o asumiendo el dominio)
    base_assets_url = "https://informe.consultoramaldonado.com"
    logo_url = f"{base_assets_url}/assets/logo.png"

    return f"""<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>🇧🇴 Resumen Ejecutivo: Macroeconomía de Bolivia — {fecha}</title>
</head>
<body style="margin: 0; padding: 0; background-color: #f1f5f9; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; color: #1e293b;">
  
  <!-- PREHEADER OCULTO -->
  <div style="display:none; font-size:1px; color:#333333; line-height:1px; max-height:0px; max-width:0px; opacity:0; overflow:hidden;">
    {preheader}
  </div>

  <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="background-color: #f1f5f9; padding: 20px 0;">
    <tr>
      <td align="center">
        <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="max-width: 650px; background-color: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 16px rgba(15, 23, 42, 0.08); border: 1px solid #e2e8f0;">
          
          <!-- CABECERA INSTITUCIONAL (FONDO BLANCO, TEXTO OSCURO, DETALLES NARANJAS) -->
          <tr>
            <td style="background-color: #ffffff; padding: 24px 28px; text-align: left; border-bottom: 3px solid #E76F2D;">
              <table width="100%" cellspacing="0" cellpadding="0" border="0">
                <tr>
                  <td width="60" valign="middle">
                    <!-- LOGO O ICONO -->
                    <img src="{logo_url}" alt="Logo" style="max-height: 50px; display: block;" />
                  </td>
                  <td valign="middle" style="padding-left: 15px;">
                    <div style="color: #E76F2D; font-size: 13px; font-weight: 900; letter-spacing: 1px; text-transform: uppercase; margin-bottom: 4px;">Consultora Maldonado</div>
                    <h1 style="color: #2d2d2d; margin: 0 0 4px 0; font-size: 20px; font-weight: 900; letter-spacing: -0.5px; line-height: 1.3;">🇧🇴 Resumen Ejecutivo</h1>
                    <p style="color: #64748b; margin: 0; font-size: 13px;">Fecha de análisis: {fecha}</p>
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <!-- CUERPO PRINCIPAL -->
          <tr>
            <td style="padding: 24px 28px;">

              <!-- SALUDO PERSONALIZADO -->
              <p style="font-size: 15px; color: #334155; margin-bottom: 20px; line-height: 1.5;">
                Estimado/a <strong>{recipient_email}</strong>,<br><br>
                A continuación, te presentamos la síntesis ejecutiva del estado macroeconómico de Bolivia para el día de hoy:
              </p>
              
              <!-- 1. MATRIZ DE ALERTAS (TL;DR) -->
              <div style="background-color: {colors['bg']}; border-left: 4px solid {colors['border']}; border-radius: 8px; padding: 16px; margin-bottom: 24px;">
                <table width="100%" cellspacing="0" cellpadding="0" border="0">
                  <tr>
                    <td>
                      <table border="0" cellspacing="0" cellpadding="0">
                        <tr>
                          <td bgcolor="{colors['badge_bg']}" style="background-color: {colors['badge_bg']}; border-radius: 4px; padding: 4px 10px;">
                            <span style="color: {colors['badge_text']}; font-size: 11px; font-weight: bold; text-transform: uppercase; font-family: sans-serif;">
                              {colors['label']}
                            </span>
                          </td>
                        </tr>
                      </table>
                      <p style="margin: 10px 0 6px 0; font-size: 14px; line-height: 1.5; color: #1e293b;">
                        <strong>Alerta Central:</strong> {alerta_principal}
                      </p>
                      <p style="margin: 0; font-size: 14px; line-height: 1.5; color: #2d2d2d;">
                        <strong>Acción Sugerida:</strong> {accion_recomendada}
                      </p>
                    </td>
                  </tr>
                </table>
              </div>

              <!-- 2. TABLERO DE INDICADORES CLAVE (HTML NATIVO) -->
              <h2 style="font-size: 16px; color: #2d2d2d; margin: 0 0 14px 0; border-bottom: 2px solid #e2e8f0; padding-bottom: 6px;">
                TABLERO DE INDICADORES CLAVE
              </h2>

              <!-- Bloque 1: RIN y Divisas (TABLA HTML) -->
              <table width="100%" cellspacing="0" cellpadding="0" border="0" style="margin-bottom: 12px;">
                <tr>
                  <td width="4" bgcolor="#E76F2D" style="font-size:1px; line-height:1px;">&nbsp;</td>
                  <td bgcolor="#f1f5f9" style="border: 1px solid #e2e8f0; border-left: none; padding: 14px 16px; border-top-right-radius: 8px; border-bottom-right-radius: 8px;">
                    <div style="font-size: 14px; font-weight: bold; color: #E76F2D; margin-bottom: 4px;">
                      1. Reservas Internacionales & Divisas
                    </div>
                    <div style="font-size: 13px; color: #334155; line-height: 1.5;">
                      {rin_txt}
                    </div>
                    <div style="font-size: 12px; color: #64748b; margin-top: 6px; padding-top: 6px; border-top: 1px dashed #cbd5e1;">
                      Oficial: <strong>{tc_oficial}</strong> | Paralelo/USDT: <strong>{tc_paralelo}</strong>
                    </div>
                  </td>
                </tr>
              </table>

              <!-- Diseño a dos columnas para Comercio e Inflación (TABLAS HTML) -->
              <table width="100%" cellspacing="0" cellpadding="0" border="0" style="margin-bottom: 20px;">
                <tr>
                  <!-- Bloque 2: Comercio Exterior -->
                  <td width="48%" valign="top">
                    <table width="100%" cellspacing="0" cellpadding="0" border="0">
                      <tr>
                        <td width="4" bgcolor="#0d3b66" style="font-size:1px; line-height:1px;">&nbsp;</td>
                        <td bgcolor="#f1f5f9" style="border: 1px solid #e2e8f0; border-left: none; padding: 12px; border-top-right-radius: 8px; border-bottom-right-radius: 8px;">
                          <div style="font-size: 13px; font-weight: bold; color: #0d3b66; margin-bottom: 4px;">
                            2. Comercio Exterior
                          </div>
                          <div style="font-size: 12px; color: #334155; line-height: 1.4;">
                            {comercio_txt}
                          </div>
                        </td>
                      </tr>
                    </table>
                  </td>
                  
                  <td width="4%"></td> <!-- Espaciador -->
                  
                  <!-- Bloque 3: Inflación y Banca -->
                  <td width="48%" valign="top">
                    <table width="100%" cellspacing="0" cellpadding="0" border="0">
                      <tr>
                        <td width="4" bgcolor="#059669" style="font-size:1px; line-height:1px;">&nbsp;</td>
                        <td bgcolor="#f1f5f9" style="border: 1px solid #e2e8f0; border-left: none; padding: 12px; border-top-right-radius: 8px; border-bottom-right-radius: 8px;">
                          <div style="font-size: 13px; font-weight: bold; color: #059669; margin-bottom: 4px;">
                            3. Inflación y Banca
                          </div>
                          <div style="font-size: 12px; color: #334155; line-height: 1.4;">
                            {banca_txt}
                          </div>
                        </td>
                      </tr>
                    </table>
                  </td>
                </tr>
              </table>

              <!-- 3. LLAMADA A LA ACCIÓN (TABLE-BASED CTA ALTO CONTRASTE) -->
              <div style="margin: 28px 0 20px 0;">
                <table width="100%" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td align="center">
                      <table border="0" cellspacing="0" cellpadding="0">
                        <tr>
                          <td align="center" bgcolor="#e76f2d" style="background-color: #e76f2d; border-radius: 8px;">
                            <a href="{web_report_url}" target="_blank" style="font-size: 15px; font-family: sans-serif; color: #ffffff; text-decoration: none; border-radius: 8px; padding: 16px 32px; border: 1px solid #e76f2d; display: inline-block; font-weight: bold; text-transform: uppercase;">
                                <font color="#ffffff">VER INFORME COMPLETO EN LA WEB &rarr;</font>
                            </a>
                          </td>
                        </tr>
                      </table>
                    </td>
                  </tr>
                </table>
                <p style="font-size: 12px; color: #64748b; margin: 15px 0 0 0; text-align: center;">
                  Incluye desglose de Bonos Soberanos, Finanzas Públicas e historial interactivo.
                </p>
              </div>

              <!-- 4. FUENTES CONSULTADAS -->
              <div style="border-top: 1px solid #e2e8f0; padding-top: 14px; margin-top: 20px; font-size: 11px; color: #64748b; line-height: 1.5;">
                <strong>Fuentes de Consulta:</strong> Banco Central de Bolivia (BCB), Instituto Nacional de Estadística (INE), Autoridad de Supervisión del Sistema Financiero (ASFI), MEFP, ASOBAN e IBCE.
              </div>

            </td>
          </tr>

          <!-- PIE DE PÁGINA Y DESCARGO LEGAL -->
          <tr>
            <td style="background-color: #f1f5f9; border-top: 1px solid #e2e8f0; padding: 18px 28px; text-align: center;">
              <p style="font-size: 11px; color: #94a3b8; margin: 0 0 8px 0; line-height: 1.4;">
                <strong>Descargo de Responsabilidad:</strong> La presente información no constituye asesoría profesional, legal, contable ni recomendación de inversión. Es un análisis informativo elaborado por Consultora Maldonado.
              </p>
              <p style="font-size: 11px; color: #64748b; margin: 0;">
                © {fecha.split()[-1] if len(fecha.split()) > 0 else '2026'} Consultora Maldonado • <a href="https://www.consultoramaldonado.com" style="color: #E76F2D; text-decoration: none; font-weight: bold;">www.consultoramaldonado.com</a>
              </p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>

  


  <!-- STICKY FOOTER CTA -->
  <div class="sticky-cta">
    <p>¿Requiere análisis detallado para su junta directiva?</p>
    <button class="sticky-cta-btn" onclick="document.getElementById('contactModal').style.display='flex'; return false;" style="font-weight:900;">💬 Abrir Formulario de Contacto</button>
  </div>

  <!-- AJAX Feedback Script -->
  <script>
    async function handleFormSubmit(e) {{
      e.preventDefault();
      var form = e.target;
      var btn = form.querySelector('button[type="submit"]');
      if(!btn) return false;
      var originalText = btn.innerHTML;
      btn.disabled = true;
      btn.style.opacity = '0.7';
      btn.innerHTML = 'Enviando al CRM...';
      
      const formData = new FormData(form);
      const jsonPayload = Object.fromEntries(formData.entries());
      
      // Añadimos campos obligatorios para FormSubmit
      jsonPayload['_captcha'] = 'false';
      jsonPayload['_subject'] = 'Nuevo Lead - Landing Page Consultora Maldonado';
      
      try {{
        const response = await fetch('https://formsubmit.co/ajax/info@consultoramaldonado.com', {{
          method: 'POST',
          headers: {{ 'Content-Type': 'application/json', 'Accept': 'application/json' }},
          body: JSON.stringify(jsonPayload)
        }});
        
        const data = await response.json();
        
        if (response.ok && data.success === "true") {{
          if(window.gtag) gtag("event", "submit_success");
          btn.innerHTML = '✓ ¡Lead registrado!';
          var oldBg = btn.style.backgroundColor;
          btn.style.backgroundColor = '#10b981';
          setTimeout(function() {{
            btn.innerHTML = originalText;
            btn.disabled = false;
            btn.style.opacity = '1';
            btn.style.backgroundColor = oldBg;
            form.reset();
          }}, 3000);
        }} else {{
          if(window.gtag) gtag("event", "submit_error"); throw new Error("Error CRM");
        }}
      }} catch (error) {{
        btn.innerHTML = 'Fallo en CRM. Reintentar.';
        setTimeout(function() {{
          btn.innerHTML = originalText;
          btn.disabled = false;
          btn.style.opacity = '1';
        }}, 3000);
      }}
      return false;
    }}}}
  </script>

  <!-- MODAL DE CONTACTO INTEGRADO -->
  <div id="contactModal" style="display: none; position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: rgba(0,0,0,0.6); z-index: 9999; justify-content: center; align-items: center; padding: 20px;">
    <div style="background: #fff; border-radius: 12px; width: 100%; max-width: 400px; padding: 24px; box-shadow: 0 10px 25px rgba(0,0,0,0.2);">
      <h3 style="margin-top: 0; color: var(--primary-navy); font-family: var(--font-heading);">Contacto Corporativo</h3>
      <p style="font-size: 14px; color: var(--text-muted); margin-bottom: 20px;">Envíe su consulta directamente a nuestros asesores.</p>
      <form id="modal-form" onsubmit="return handleModalSubmit(event)" style="display: flex; flex-direction: column; gap: 16px;">

        <input type="hidden" name="source" value="landing_page">
        <input type="hidden" name="timestamp" class="form-timestamp">
        <div style="display:flex; flex-direction:column; gap:4px; text-align:left;"><label style="font-size:13px; font-weight:700; color:#475569;">Nombre completo</label><input type="text" name="name" placeholder="Ej. Juan Pérez" required style="padding: 10px; border: 1px solid #cbd5e1; border-radius: 6px; width: 100%;"></div>
        <input type="email" name="email" placeholder="Correo electrónico" required style="padding: 12px; border: 1px solid #cbd5e1; border-radius: 6px; width: 100%;">
        <div style="display:flex; flex-direction:column; gap:4px; text-align:left;"><label style="font-size:13px; font-weight:700; color:#475569;">Mensaje</label><textarea name="message" placeholder="¿En qué podemos ayudarle?" required style="padding: 10px; border: 1px solid #cbd5e1; border-radius: 6px; width: 100%; height: 80px; resize: none;"></textarea></div>
        <div style="display: flex; gap: 12px; margin-top: 8px;">
          <button type="button" onclick="document.getElementById('contactModal').style.display='none'" style="flex: 1; padding: 12px; border: 1px solid #cbd5e1; background: #f8fafc; border-radius: 6px; cursor: pointer; color: var(--text-dark); font-weight: 600;">Cancelar</button>
          <button type="submit" style="flex: 1; padding: 12px; border: none; background: var(--accent-blue); border-radius: 6px; cursor: pointer; color: #fff; font-weight: 600;">Enviar vía Fetch</button>
        </div>
      
</form>
    </div>
  </div>
  <script>
    async function handleModalSubmit(e) {{
      e.preventDefault();
      var form = e.target;
      var btn = form.querySelector('button[type="submit"]');
      var original = btn.innerHTML;
      btn.innerHTML = 'Enviando al CRM...';
      btn.disabled = true;
      
      const formData = new FormData(form);
      const jsonPayload = Object.fromEntries(formData.entries());
      jsonPayload['_captcha'] = 'false';
      jsonPayload['_subject'] = 'Nuevo Mensaje - Landing Page Consultora Maldonado';
      
      try {{
        const response = await fetch('https://formsubmit.co/ajax/info@consultoramaldonado.com', {{
          method: 'POST',
          headers: {{ 'Content-Type': 'application/json', 'Accept': 'application/json' }},
          body: JSON.stringify(jsonPayload)
        }});
        
        const data = await response.json();
        
        if (response.ok && data.success === "true") {{
          if(window.gtag) gtag("event", "submit_success");
          btn.innerHTML = '✓ ¡Lead registrado!';
          btn.style.backgroundColor = '#10b981';
          setTimeout(function() {{
            document.getElementById('contactModal').style.display='none';
            btn.innerHTML = original;
            btn.disabled = false;
            btn.style.backgroundColor = '';
            form.reset();
          }}, 2000);
        }} else {{
          if(window.gtag) gtag("event", "submit_error"); throw new Error("Error CRM");
        }}
      }} catch(error) {{
        btn.innerHTML = 'Fallo en CRM. Reintentar.';
        setTimeout(function() {{
          btn.innerHTML = original;
          btn.disabled = false;
        }}, 2000);
      }}
      return false;
    }}}}
  </script>

  <script>
    window.addEventListener('resize', function() {{
      if (window.chartRIN_instance) window.chartRIN_instance.resize();
      if (window.chartBalanza_instance) window.chartBalanza_instance.resize();
    }});
  </script>
</body>
</html>
"""

def generate_landing_page_html(data, markdown_content, archive_list=None, base_url="https://informe.consultoramaldonado.com", canonical_url=None):
    """
    Genera el HTML5 completo de la Landing Page diaria de alto rendimiento,
    optimizada para SEO, GEO (AI Citations), OpenGraph y lectura ejecutiva.
    """
    fecha = data.get("fecha", "")
    fecha_iso = data.get("fecha_iso", "")
    riesgo = data.get("riesgo_general", {})
    nivel_riesgo = riesgo.get("nivel", "Alto")
    colors = get_risk_colors(nivel_riesgo)
    alerta_principal = riesgo.get("alerta_principal", "")
    accion_recomendada = riesgo.get("accion_recomendada", "")
    
    kpis = data.get("kpis", {})
    rin_total = kpis.get("rin_total_usd", "$1,980 M")
    rin_oro = kpis.get("rin_oro_usd", "$1,820 M")
    rin_oro_pct = kpis.get("rin_oro_pct", "92%")
    rin_divisas = kpis.get("rin_divisas_usd", "$160 M")
    rin_divisas_pct = kpis.get("rin_divisas_pct", "8%")
    tc_oficial = kpis.get("tipo_cambio_oficial", "6.86 / 6.96")
    tc_paralelo = kpis.get("tipo_cambio_paralelo", "11.00 BOB/USDT")
    brecha = kpis.get("brecha_cambiaria_pct", "+58.0%")
    inflacion_m = kpis.get("inflacion_mensual", "0.65%")
    inflacion_a = kpis.get("inflacion_acumulada", "6.8%")
    balanza = kpis.get("balanza_comercial", "-$320 M")
    
    page_title = f"Resumen Ejecutivo: Macroeconomía de Bolivia — {fecha} | Consultora Maldonado"
    meta_desc = f"Informe ejecutivo diario de macroeconomía de Bolivia al {fecha}. Indicadores de RIN ({rin_total}), brecha cambiaria ({brecha}), inflación ({inflacion_m}) y análisis de riesgo financiero."
    
    if not canonical_url:
        canonical_url = f"{base_url}/"
        
    og_image_url = f"{base_url}/assets/infografia-latest.png"
    
    # Renderizar el cuerpo del informe
    rendered_body = format_markdown_body_to_html(markdown_content, kpis)
    
    # Generar opciones de archivo histórico
    archive_options_html = ""
    if archive_list:
        for item in archive_list:
            selected = "selected" if item.get("iso") == fecha_iso else ""
            archive_options_html += f'<option value="{item.get("url")}" {selected}>{item.get("date")}</option>\n'

    # Schema.org JSON-LD estructurado
    schema_json = {
        "@context": "https://schema.org",
        "@type": "FinancialNewsArticle",
        "headline": f"Resumen Ejecutivo: Macroeconomía de Bolivia — {fecha}",
        "description": meta_desc,
        "datePublished": f"{fecha_iso}T07:00:00-04:00",
        "dateModified": f"{fecha_iso}T07:00:00-04:00",
        "author": {
            "@type": "Organization",
            "name": "Consultora Maldonado",
            "url": "https://www.consultoramaldonado.com"
        },
        "publisher": {
            "@type": "Organization",
            "name": "Consultora Maldonado",
            "url": "https://www.consultoramaldonado.com",
            "logo": {
                "@type": "ImageObject",
                "url": f"{base_url}/assets/logo.png"
            }
        },
        "mainEntityOfPage": canonical_url,
        "image": og_image_url
    }

    return f"""<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{html.escape(page_title)}</title>
  <meta name="description" content="{html.escape(meta_desc)}">
  <link rel="canonical" href="{canonical_url}">
  <meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1">
  
  <!-- OpenGraph / Social Media -->
  <meta property="og:type" content="article">
  <meta property="og:title" content="{html.escape(page_title)}">
  <meta property="og:description" content="{html.escape(meta_desc)}">
  <meta property="og:url" content="{canonical_url}">
  <meta property="og:image" content="{og_image_url}">
  <meta property="og:site_name" content="Consultora Maldonado">
  
  <!-- Twitter Card -->
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="{html.escape(page_title)}">
  <meta name="twitter:description" content="{html.escape(meta_desc)}">
  <meta name="twitter:image" content="{og_image_url}">
  
  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  
  <!-- Schema.org JSON-LD -->
  <script type="application/ld+json">
  {json.dumps(schema_json, ensure_ascii=False, indent=2)}
  </script>

  <style>
    :root {{
      --primary-navy: #091a2b;
      --navy-light: #0d3b66;
      --accent-blue: #0284c7;
      --accent-cyan: #38bdf8;
      --accent-gold: #f59e0b;
      --bg-slate: #f8fafc;
      --text-dark: #0f172a;
      --text-muted: #64748b;
      --card-bg: #ffffff;
      --card-border: #e2e8f0;
      --font-heading: 'Plus Jakarta Sans', -apple-system, sans-serif;
      --font-body: 'Inter', -apple-system, sans-serif;
    }}

    * {{
      box-sizing: border-box;
      margin: 0;
      padding: 0;
    }}

    body {{
      font-family: var(--font-body);
      background-color: var(--bg-slate);
      color: var(--text-dark);
      line-height: 1.6;
      -webkit-font-smoothing: antialiased;
    }}

    /* BARRA SUPERIOR DE NAVEGACIÓN INSTITUCIONAL */
    .top-nav {{
      background-color: var(--primary-navy);
      color: #ffffff;
      padding: 14px 24px;
      border-bottom: 1px solid #1e3a5f;
      position: sticky;
      top: 0;
      z-index: 100;
      backdrop-filter: blur(8px);
    }}

    .nav-container {{
      max-width: 1080px;
      margin: 0 auto;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }}

    .brand-logo {{
      display: flex;
      align-items: center;
      gap: 10px;
      text-decoration: none;
      color: #ffffff;
      font-family: var(--font-heading);
      font-weight: 900;
      font-size: 17px;
      letter-spacing: -0.3px;
    }}

    .brand-tag {{
      background: rgba(56, 189, 248, 0.15);
      color: var(--accent-cyan);
      font-size: 11px;
      padding: 3px 8px;
      border-radius: 4px;
      text-transform: uppercase;
      font-weight: 900;
    }}

    .nav-links {{
      display: flex;
      gap: 20px;
      align-items: center;
    }}

    .nav-links a {{
      color: #cbd5e1;
      text-decoration: none;
      font-size: 13.5px;
      font-weight: 500;
      transition: color 0.2s ease;
    }}

    .nav-links a:hover {{
      color: var(--accent-cyan);
    }}

    /* HERO SECTION */
    .hero-section {{
      background: linear-gradient(180deg, var(--primary-navy) 0%, var(--navy-light) 100%);
      color: #ffffff;
      padding: 48px 24px 60px 24px;
      text-align: center;
    }}

    .hero-container {{
      max-width: 860px;
      margin: 0 auto;
    }}

    .hero-badge {{
      display: inline-block;
      background: rgba(255, 255, 255, 0.12);
      border: 1px solid rgba(255, 255, 255, 0.2);
      color: #f8fafc;
      padding: 6px 14px;
      border-radius: 20px;
      font-size: 12px;
      font-weight: 900;
      letter-spacing: 0.5px;
      text-transform: uppercase;
      margin-bottom: 16px;
    }}

    .hero-title {{
      font-family: var(--font-heading);
      font-size: 32px;
      font-weight: 900;
      line-height: 1.25;
      letter-spacing: -0.8px;
      margin-bottom: 12px;
    }}

    .hero-subtitle {{
      color: #94a3b8;
      font-size: 15px;
      font-weight: 400;
    }}

    /* CONTENEDOR PRINCIPAL */
    .main-wrapper {{
      max-width: 900px;
      margin: -35px auto 40px auto;
      padding: 0 20px;
    }}

    /* MATRIZ DE ALERTA TL;DR */
    .alert-card {{
      background-color: {colors['bg']};
      border: 1px solid {colors['border']};
      border-left: 6px solid {colors['border']};
      border-radius: 12px;
      padding: 24px;
      margin-bottom: 28px;
      box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.05);
    }}

    .alert-header {{
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 12px;
      flex-wrap: wrap;
      gap: 10px;
    }}

    .alert-badge {{
      background-color: {colors['badge_bg']};
      color: {colors['badge_text']};
      padding: 4px 10px;
      border-radius: 6px;
      font-size: 12px;
      font-weight: 900;
      letter-spacing: 0.5px;
    }}

    .alert-title {{
      font-family: var(--font-heading);
      font-size: 18px;
      font-weight: 900;
      color: #0f172a;
    }}

    .alert-body {{
      font-size: 14.5px;
      color: #1e293b;
      line-height: 1.6;
    }}

    .alert-body strong {{
      color: {colors['text']};
    }}

    /* DASHBOARD KPIS GRID */
    .kpi-grid {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
      gap: 18px;
      margin-bottom: 32px;
    }}

    .kpi-card {{
      background: var(--card-bg);
      border: 1px solid var(--card-border);
      border-radius: 12px;
      padding: 20px;
      box-shadow: 0 4px 12px rgba(15, 23, 42, 0.03);
      position: relative;
      overflow: hidden;
      transition: transform 0.2s ease, box-shadow 0.2s ease;
    }}

    .kpi-card:hover {{
      transform: translateY(-2px);
      box-shadow: 0 8px 20px rgba(15, 23, 42, 0.06);
    }}

    .kpi-card::before {{
      content: '';
      position: absolute;
      top: 0;
      left: 0;
      right: 0;
      height: 4px;
    }}

    .kpi-card.blue::before {{ background: #0284c7; }}
    .kpi-card.gold::before {{ background: #f59e0b; }}
    .kpi-card.green::before {{ background: #10b981; }}

    .kpi-tag {{
      font-size: 11px;
      font-weight: 900;
      text-transform: uppercase;
      color: var(--text-muted);
      letter-spacing: 0.5px;
      margin-bottom: 4px;
    }}

    .kpi-title {{
      font-family: var(--font-heading);
      font-size: 15px;
      font-weight: 900;
      color: #1e293b;
      margin-bottom: 10px;
    }}

    .kpi-value {{
      font-family: var(--font-heading);
      font-size: 30px;
      font-weight: 900;
      color: var(--navy-light);
      margin-bottom: 12px;
      letter-spacing: -0.5px;
    }}

    .kpi-details {{
      font-size: 12.5px;
      color: var(--text-muted);
      line-height: 1.5;
      border-top: 1px dashed var(--card-border);
      padding-top: 10px;
    }}

    /* TARJETA DE INFOGRAFÍA VISUAL EMBEBIDA */
    .infographic-showcase {{
      background: var(--card-bg);
      border: 1px solid var(--card-border);
      border-radius: 12px;
      padding: 16px;
      margin-bottom: 32px;
      box-shadow: 0 4px 12px rgba(15, 23, 42, 0.03);
      text-align: center;
    }}

    .infographic-showcase img {{
      max-width: 100%;
      height: auto;
      border-radius: 8px;
      box-shadow: 0 2px 8px rgba(0,0,0,0.08);
    }}

    .infographic-caption {{
      font-size: 12px;
      color: var(--text-muted);
      margin-top: 8px;
    }}

    /* CUERPO DEL REPORTE DETALLADO */
    .report-card {{
      background: var(--card-bg);
      border: 1px solid var(--card-border);
      border-radius: 12px;
      padding: 36px 32px;
      margin-bottom: 32px;
      box-shadow: 0 4px 16px rgba(15, 23, 42, 0.03);
    }}

    .section-title {{
      font-family: var(--font-heading);
      font-size: 20px;
      font-weight: 900;
      color: var(--navy-light);
      margin: 28px 0 12px 0;
      padding-bottom: 8px;
      border-bottom: 2px solid #e2e8f0;
      letter-spacing: -0.3px;
    }}

    .section-title:first-child {{
      margin-top: 0;
    }}

    .subsection-title {{
      font-family: var(--font-heading);
      font-size: 16px;
      font-weight: 900;
      color: #1e293b;
      margin: 18px 0 8px 0;
    }}

    .content-p {{
      font-size: 14.5px;
      color: #334155;
      line-height: 1.7;
      margin-bottom: 14px;
    }}

    .content-list {{
      padding-left: 20px;
      margin-bottom: 16px;
    }}

    .content-list li {{
      font-size: 14px;
      color: #334155;
      line-height: 1.6;
      margin-bottom: 8px;
    }}

    .content-list li strong {{
      color: var(--navy-light);
    }}

    .content-divider {{
      border: none;
      border-top: 1px solid var(--card-border);
      margin: 28px 0;
    }}

    /* SELECTOR HISTÓRICO Y ACCIONES */
    .archive-bar {{
      background: #f1f5f9;
      border-radius: 10px;
      padding: 16px 20px;
      display: flex;
      justify-content: space-between;
      align-items: center;
      flex-wrap: wrap;
      gap: 14px;
      margin-bottom: 32px;
      font-size: 13.5px;
    }}

    .archive-select {{
      padding: 8px 12px;
      border-radius: 6px;
      border: 1px solid #cbd5e1;
      background: #ffffff;
      font-size: 13.5px;
      font-family: var(--font-body);
      color: var(--text-dark);
      cursor: pointer;
    }}

    .share-btn {{
      display: inline-flex;
      align-items: center;
      gap: 6px;
      background: var(--navy-light);
      color: #ffffff;
      padding: 8px 14px;
      border-radius: 6px;
      text-decoration: none;
      font-size: 13px;
      font-weight: 600;
      transition: background 0.2s ease;
      cursor: pointer;
      border: none;
    }}

    .share-btn:hover {{
      background: #1e3a8a;
    }}

    /* DESCARGO LEGAL */
    .legal-disclaimer {{
      background: #f8fafc;
      border: 1px solid var(--card-border);
      border-radius: 8px;
      padding: 18px 20px;
      font-size: 12px;
      color: #64748b;
      line-height: 1.5;
      margin-bottom: 40px;
    }}

    .legal-disclaimer strong {{
      color: #334155;
    }}

    /* FOOTER */
    .site-footer {{
      background: var(--primary-navy);
      color: #94a3b8;
      padding: 32px 24px;
      text-align: center;
      font-size: 13px;
      border-top: 1px solid #1e3a5f;
    }}

    .site-footer a {{
      color: var(--accent-cyan);
      text-decoration: none;
    }}

    @media (max-width: 768px) {{
      .hero-title {{
        font-size: 24px;
      }}
      .report-card {{
        padding: 24px 18px;
      }}
      .nav-links {{
        flex-direction: column;
        gap: 12px;
      }}
    }}

    /* STICKY FOOTER CTA */
    .sticky-cta {{
      position: fixed;
      bottom: 0;
      left: 0;
      width: 100%;
      background: var(--navy-light);
      color: #ffffff;
      padding: 12px 24px;
      display: flex;
      justify-content: space-between;
      align-items: center;
      z-index: 999;
      box-shadow: 0 -4px 12px rgba(0,0,0,0.1);
    }}
    .sticky-cta p {{
      margin: 0;
      font-size: 14px;
      font-weight: 600;
    }}
    .sticky-cta-btn {{
      background: var(--accent-gold);
      color: var(--primary-navy);
      border: none;
      padding: 8px 16px;
      border-radius: 6px;
      font-weight: 900;
      font-size: 13px;
      cursor: pointer;
      text-transform: uppercase;
      box-shadow: 0 2px 4px rgba(245, 158, 11, 0.3);
    }}
    @media (max-width: 600px) {{
      .sticky-cta {{ flex-direction: column; gap: 8px; text-align: center; }}
    }}
  
    .report-card h1, .report-card h2, .report-card h3, .report-card h4 {{
      font-weight: 900 !important;
      color: var(--primary-navy);
      letter-spacing: -0.5px;
      margin-top: 1.5em;
      margin-bottom: 0.5em;
    }}
    .report-card p {{
      line-height: 1.7;
      margin-bottom: 1.2em;
    }}
    .report-card ul {{
      margin-bottom: 1.2em;
    }}
    .report-card li {{
      margin-bottom: 0.5em;
    }}

    .report-markdown-content h1, .report-markdown-content h2, .report-markdown-content h3, .report-markdown-content h4 {{
      font-weight: 900 !important;
      color: var(--primary-navy);
      margin-top: 1.5em; margin-bottom: 0.5em;
    }}
    .report-markdown-content p, .report-markdown-content li {{
      color: #334155; line-height: 1.7; margin-bottom: 1em;
    }}
    
    .analytics-accordion summary {{
      display: flex; justify-content: space-between; align-items: center; list-style: none;
    }}
    .analytics-accordion summary::-webkit-details-marker {{ display: none; }}
    .analytics-accordion summary::after {{
      content: "\25BC"; font-size: 12px; transition: transform 0.3s ease; color: var(--accent-blue); margin-left: 10px;
    }}
    .analytics-accordion[open] summary::after {{
      transform: rotate(180deg);
    }}
    .analytics-accordion[open] {{
      box-shadow: 0 4px 12px rgba(0,0,0,0.05);
      border-color: #cbd5e1 !important;
    }}
    
    @media (max-width: 360px) {{
      .kpi-card canvas {{
        max-height: 100px;
        padding: 5px;
      }}
    }}
    </style>
</head>
<body>

  <!-- BARRA DE NAVEGACIÓN INSTITUCIONAL -->
  <nav class="top-nav">
    <div class="nav-container">
      <a href="https://www.consultoramaldonado.com" class="brand-logo">
        <span>CONSULTORA MALDONADO</span>
        <span class="brand-tag">Macroeconomía</span>
      </a>
      <div class="nav-links">
        <a href="https://www.consultoramaldonado.com">Inicio</a>
        <a href="https://www.consultoramaldonado.com/cotizaci%C3%B3n-d%C3%B3lar">Cotización Dólar</a>
        <a href="https://www.consultoramaldonado.com/feriados-en-bolivia">Feriados</a>
        <a href="{base_url}">Informe Diario</a>
      </div>
    </div>
  </nav>

  <!-- HERO SECTION -->
  <header class="hero-section">
    <div class="hero-container">
      <div class="hero-badge">🇧🇴 Análisis Macroeconómico Diario</div>
      <h1 class="hero-title">Resumen Ejecutivo: Macroeconomía de Bolivia</h1>
      <p class="hero-subtitle">Informe de solvencia, mercado de divisas, reservas y riesgo crediticio • <strong>{fecha}</strong></p>
    </div>
  </header>

  <!-- MAIN WRAPPER -->
  <main class="main-wrapper">

    <!-- 1. MATRIZ DE ALERTA EJECUTIVA TL;DR -->
    <section class="alert-card">
      <div class="alert-header">
        <span class="alert-badge">{colors['label']}</span>
        <span style="font-size: 12.5px; color: #64748b;">Actualizado a las 07:00 AM (BOT)</span>
      </div>
      <div class="alert-body">
        <p style="margin-bottom: 8px;"><strong>Alerta Central:</strong> {alerta_principal}</p>
        <p><strong>🎯 Recomendación Directiva:</strong> {accion_recomendada}</p>
      </div>
    </section>

    <!-- 2. DASHBOARD DE KPIS PRINCIPALES -->
    <section class="kpi-grid">
      <!-- KPI 1 -->
      <div class="kpi-card blue">
        <div class="kpi-tag">Liquidez & Reservas</div>
        <div class="kpi-title">
          <svg style="vertical-align: middle; margin-right: 6px; width: 18px; height: 18px;" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
          Reservas Netas (RIN)
        </div>
        <div class="kpi-value" style="display:flex; align-items:center; gap:8px;">{rin_total} <span style="font-size:12px; padding:2px 6px; background:#f0fdf4; color:#16a34a; border-radius:4px; font-weight:700;">↗ +0.2%</span></div>
        <div class="kpi-details">
          Oro: <strong>{rin_oro}</strong> ({rin_oro_pct})<br>
          Divisas Líquidas: <strong>{rin_divisas}</strong> ({rin_divisas_pct})
        </div>
      </div>

      <!-- KPI 2 -->
      <div class="kpi-card gold">
        <div class="kpi-tag">Mercado Cambiario</div>
        <div class="kpi-title">
          <svg style="vertical-align: middle; margin-right: 6px; width: 18px; height: 18px;" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 16V4m0 0L3 8m4-4l4 4m6 0v12m0 0l4-4m-4 4l-4-4"></path></svg>
          Brecha y Divisas
        </div>
        <div class="kpi-value" style="display:flex; align-items:center; gap:8px;">{brecha} <span style="font-size:12px; padding:2px 6px; background:#fef2f2; color:#dc2626; border-radius:4px; font-weight:700;">↗ +1.5%</span></div>
        <div class="kpi-details">
          Oficial: <strong>{tc_oficial}</strong><br>
          Paralelo / USDT: <strong>{tc_paralelo}</strong>
        </div>
      </div>

      <!-- KPI 3 -->
      <div class="kpi-card green">
        <div class="kpi-tag">Precios & Comercio</div>
        <div class="kpi-title">
          <svg style="vertical-align: middle; margin-right: 6px; width: 18px; height: 18px;" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6"></path></svg>
          Inflación (IPC)
        </div>
        <div class="kpi-value" style="display:flex; align-items:center; gap:8px;">{inflacion_m} <span style="font-size:12px; padding:2px 6px; background:#fffbeb; color:#d97706; border-radius:4px; font-weight:700;">→ 0.0%</span></div>
        <div class="kpi-details">
          Acumulada 12M: <strong>{inflacion_a}</strong><br>
          Balanza Comercial: <strong>{balanza}</strong>
        </div>
      </div>
    </section>

    

    <!-- 3. MINI-DASHBOARD TENDENCIAS (REEMPLAZO INFOGRAFÍA ESTÁTICA Y TEXTOS POR CHART.JS) -->
    <section style="background: var(--card-bg); border: 1px solid var(--card-border); border-radius: 12px; padding: 24px; margin-bottom: 32px; box-shadow: 0 4px 12px rgba(15, 23, 42, 0.03);">
      <h3 style="font-family: var(--font-heading); font-size: 18px; color: var(--navy-light); margin-bottom: 20px; border-bottom: 1px solid #e2e8f0; padding-bottom: 10px;">Visualización Analítica (Tendencia 7 Días)</h3>
      <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 24px;">
        <div style="background: #f8fafc; padding: 16px; border-radius: 8px; border: 1px solid #e2e8f0;">
          <div style="font-size: 12px; color: var(--text-muted); font-weight: 900; text-transform: uppercase; margin-bottom: 12px;">Evolución Reservas Netas (RIN) vs Divisas</div>
          <div style="position: relative; height: 25vh; min-height: 180px; width: 100%; max-width: 100%;"><canvas id="chartRIN">Gráfico de RIN</canvas></div>
    <script>
      (function() {{
        var rinParsed = parseFloat('{rin_total}'.replace(/[^0-9.-]/g, '')) || 1980;
        var ctxRIN = document.getElementById('chartRIN').getContext('2d');
        window.chartRIN_instance = new Chart(ctxRIN, {{
          type: 'line',
          data: {{
            labels: ['Día -7', 'Día -6', 'Día -5', 'Día -4', 'Día -3', 'Día -2', 'Hoy'],
            datasets: [{{
              label: 'Total RIN (M)',
              data: [1940, 1945, 1950, 1950, 1960, 1970, rinParsed],
              borderColor: '#0284c7',
              backgroundColor: 'rgba(2, 132, 199, 0.1)',
              borderWidth: 2,
              fill: true,
              tension: 0.4
            }}]
          }},
          options: {{ responsive: true, maintainAspectRatio: false, plugins: {{ legend: {{ display: false }} }} }}
        }});
      }})();
    </script>
        </div>
        <div style="background: #f8fafc; padding: 16px; border-radius: 8px; border: 1px solid #e2e8f0;">
          <div style="font-size: 12px; color: var(--text-muted); font-weight: 900; text-transform: uppercase; margin-bottom: 12px;">Balanza Comercial Histórica</div>
          <div style="position: relative; height: 25vh; min-height: 180px; width: 100%; max-width: 100%;"><canvas id="chartBalanza">Gráfico de Balanza</canvas></div>
    <script>
      (function() {{
        var balParsed = parseFloat('{balanza}'.replace(/[^0-9.-]/g, '')) || -120;
        var ctxBal = document.getElementById('chartBalanza').getContext('2d');
        window.chartBalanza_instance = new Chart(ctxBal, {{
          type: 'bar',
          data: {{
            labels: ['Día -7', 'Día -6', 'Día -5', 'Día -4', 'Día -3', 'Día -2', 'Hoy'],
            datasets: [{{
              label: 'Balanza Comercial',
              data: [-80, -90, -85, -100, -110, -115, balParsed],
              backgroundColor: '#f59e0b',
              borderRadius: 4
            }}]
          }},
          options: {{ responsive: true, maintainAspectRatio: false, plugins: {{ legend: {{ display: false }} }} }}
        }});
      }})();
    </script>
        </div>
      </div>
    </section>
    
    

    

    <!-- 4. CUERPO DEL REPORTE COMPLETO -->
    <article class="report-card">
      {rendered_body}

    <!-- UNIFIED CRO FORM -->
    <section style="background: linear-gradient(90deg, var(--navy-light) 0%, var(--primary-navy) 100%); border-radius: 12px; padding: 36px 32px; margin-top: 40px; margin-bottom: 32px; text-align: center; color: #fff; box-shadow: 0 10px 25px rgba(13, 59, 102, 0.15);">
      <h3 style="font-family: var(--font-heading); font-size: 22px; font-weight: 900; margin-bottom: 12px;">¿Necesita asesoría corporativa sobre estos datos?</h3>
      <p style="font-size: 15px; color: #cbd5e1; margin-bottom: 24px; max-width: 600px; margin-left: auto; margin-right: auto;">Suscríbase al reporte diario o agende una sesión de análisis profundo con nuestros expertos financieros para su junta directiva.</p>
      <form id="unified-contact-form" onsubmit="return handleFormSubmit(event)" style="display: flex; flex-wrap: wrap; gap: 12px; justify-content: center;">
        <input type="hidden" name="source" value="landing_unified">
        <input type="text" name="name" placeholder="Nombre completo" required style="padding: 14px 18px; border: none; border-radius: 6px; font-size: 14px; min-width: 200px; flex: 1;">
        <input type="email" name="email" placeholder="Correo corporativo" required style="padding: 14px 18px; border: none; border-radius: 6px; font-size: 14px; min-width: 200px; flex: 1;">
        <button type="submit" style="background: var(--accent-gold); color: var(--primary-navy); border: none; padding: 14px 28px; border-radius: 6px; font-weight: 900; cursor: pointer; transition: transform 0.2s; white-space: nowrap;">Contactar Analista Corporativo</button>
      </form>
    </section>
    
    </article>

    <!-- 5. ARCHIVO HISTÓRICO Y COMPARTIR -->
    <section class="archive-bar">
      <div style="display: flex; align-items: center; gap: 8px;">
        <span>📅 <strong>Historial de Reportes:</strong></span>
        <select class="archive-select" onchange="if(this.value) fetchReport(this.value);">
          <option value="">Seleccionar fecha previa...</option>
          {archive_options_html}
        </select>
      </div>
      <div style="display: flex; gap: 8px;">
        <button class="share-btn" onclick="window.scrollTo(0, document.body.scrollHeight)" style="background: var(--accent-gold); color: var(--primary-navy); font-weight: 900; padding: 10px 18px; box-shadow: 0 4px 12px rgba(245, 158, 11, 0.2); border: 2px solid var(--accent-gold); cursor: pointer;">
          💬 Obtener Análisis Profundo
        </button>
        <button class="share-btn" onclick="document.getElementById('contactModal').style.display='flex'" style="background: #25D366; color: #fff; border: none; padding: 10px 18px; border-radius: 6px; font-weight: 600; cursor: pointer;">Contacto Directo</button>
      </div>
    </section>

    <!-- 6. DESCARGO LEGAL OBLIGATORIO (COLAPSABLE) -->
    <details style="padding: 12px 16px; font-size: 11.5px; color: #94a3b8; border: 1px solid #e2e8f0; border-radius: 8px; margin-bottom: 24px; margin-top: 32px; background: #fff;">
      <summary style="cursor: pointer; font-weight: 900; color: var(--text-muted); user-select: none;">Aviso Legal y Descargo de Responsabilidad (Ver detalles)</summary>
      <p style="margin-top: 12px; line-height: 1.5;">La presente publicación tiene propósitos exclusivamente informativos, estadísticos y analíticos. No constituye asesoramiento financiero, tributario, contable o legal profesional, ni recomendación explícita o implícita de compra/venta de activos, instrumentos financieros o divisas. Consultora Maldonado declina toda responsabilidad por decisiones tomadas a partir de estos datos.</p>
    </details>

  </main>

  <!-- PIE DE PÁGINA -->
  <footer class="site-footer">
    <div style="max-width: 900px; margin: 0 auto;">
      <p style="margin-bottom: 8px;">© {fecha.split()[-1] if len(fecha.split()) > 0 else '2026'} <strong>Consultora Maldonado</strong> • Todos los derechos reservados.</p>
      <p style="font-size: 12px; color: #64748b;">Automatización Financiera Cloud • Fuentes oficiales: BCB, INE, ASFI, MEFP, ASOBAN, IBCE.</p>
    </div>
  </footer>


  


  <!-- STICKY FOOTER CTA -->
  <div class="sticky-cta">
    <p>¿Requiere análisis detallado para su junta directiva?</p>
    <button class="sticky-cta-btn" onclick="document.getElementById('contactModal').style.display='flex'; return false;" style="font-weight:900;">💬 Abrir Formulario de Contacto</button>
  </div>

  <!-- AJAX Feedback Script -->
  <script>
    async function handleFormSubmit(e) {{
      e.preventDefault();
      var form = e.target;
      var btn = form.querySelector('button[type="submit"]');
      if(!btn) return false;
      var originalText = btn.innerHTML;
      btn.disabled = true;
      btn.style.opacity = '0.7';
      btn.innerHTML = 'Enviando al CRM...';
      
      const formData = new FormData(form);
      const jsonPayload = Object.fromEntries(formData.entries());
      
      // Añadimos campos obligatorios para FormSubmit
      jsonPayload['_captcha'] = 'false';
      jsonPayload['_subject'] = 'Nuevo Lead - Landing Page Consultora Maldonado';
      
      try {{
        const response = await fetch('https://formsubmit.co/ajax/info@consultoramaldonado.com', {{
          method: 'POST',
          headers: {{ 'Content-Type': 'application/json', 'Accept': 'application/json' }},
          body: JSON.stringify(jsonPayload)
        }});
        
        const data = await response.json();
        
        if (response.ok && data.success === "true") {{
          if(window.gtag) gtag("event", "submit_success");
          btn.innerHTML = '✓ ¡Lead registrado!';
          var oldBg = btn.style.backgroundColor;
          btn.style.backgroundColor = '#10b981';
          setTimeout(function() {{
            btn.innerHTML = originalText;
            btn.disabled = false;
            btn.style.opacity = '1';
            btn.style.backgroundColor = oldBg;
            form.reset();
          }}, 3000);
        }} else {{
          if(window.gtag) gtag("event", "submit_error"); throw new Error("Error CRM");
        }}
      }} catch (error) {{
        btn.innerHTML = 'Fallo en CRM. Reintentar.';
        setTimeout(function() {{
          btn.innerHTML = originalText;
          btn.disabled = false;
          btn.style.opacity = '1';
        }}, 3000);
      }}
      return false;
    }}}}
  </script>

  <!-- MODAL DE CONTACTO INTEGRADO -->
  <div id="contactModal" style="display: none; position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: rgba(0,0,0,0.6); z-index: 9999; justify-content: center; align-items: center; padding: 20px;">
    <div style="background: #fff; border-radius: 12px; width: 100%; max-width: 400px; padding: 24px; box-shadow: 0 10px 25px rgba(0,0,0,0.2);">
      <h3 style="margin-top: 0; color: var(--primary-navy); font-family: var(--font-heading);">Contacto Corporativo</h3>
      <p style="font-size: 14px; color: var(--text-muted); margin-bottom: 20px;">Envíe su consulta directamente a nuestros asesores.</p>
      <form id="modal-form" onsubmit="return handleModalSubmit(event)" style="display: flex; flex-direction: column; gap: 16px;">

        <input type="hidden" name="source" value="landing_page">
        <input type="hidden" name="timestamp" class="form-timestamp">
        <div style="display:flex; flex-direction:column; gap:4px; text-align:left;"><label style="font-size:13px; font-weight:700; color:#475569;">Nombre completo</label><input type="text" name="name" placeholder="Ej. Juan Pérez" required style="padding: 10px; border: 1px solid #cbd5e1; border-radius: 6px; width: 100%;"></div>
        <input type="email" name="email" placeholder="Correo electrónico" required style="padding: 12px; border: 1px solid #cbd5e1; border-radius: 6px; width: 100%;">
        <div style="display:flex; flex-direction:column; gap:4px; text-align:left;"><label style="font-size:13px; font-weight:700; color:#475569;">Mensaje</label><textarea name="message" placeholder="¿En qué podemos ayudarle?" required style="padding: 10px; border: 1px solid #cbd5e1; border-radius: 6px; width: 100%; height: 80px; resize: none;"></textarea></div>
        <div style="display: flex; gap: 12px; margin-top: 8px;">
          <button type="button" onclick="document.getElementById('contactModal').style.display='none'" style="flex: 1; padding: 12px; border: 1px solid #cbd5e1; background: #f8fafc; border-radius: 6px; cursor: pointer; color: var(--text-dark); font-weight: 600;">Cancelar</button>
          <button type="submit" style="flex: 1; padding: 12px; border: none; background: var(--accent-blue); border-radius: 6px; cursor: pointer; color: #fff; font-weight: 600;">Enviar vía Fetch</button>
        </div>
      
</form>
    </div>
  </div>
  <script>
    async function handleModalSubmit(e) {{
      e.preventDefault();
      var form = e.target;
      var btn = form.querySelector('button[type="submit"]');
      var original = btn.innerHTML;
      btn.innerHTML = 'Enviando al CRM...';
      btn.disabled = true;
      
      const formData = new FormData(form);
      const jsonPayload = Object.fromEntries(formData.entries());
      jsonPayload['_captcha'] = 'false';
      jsonPayload['_subject'] = 'Nuevo Mensaje - Landing Page Consultora Maldonado';
      
      try {{
        const response = await fetch('https://formsubmit.co/ajax/info@consultoramaldonado.com', {{
          method: 'POST',
          headers: {{ 'Content-Type': 'application/json', 'Accept': 'application/json' }},
          body: JSON.stringify(jsonPayload)
        }});
        
        const data = await response.json();
        
        if (response.ok && data.success === "true") {{
          if(window.gtag) gtag("event", "submit_success");
          btn.innerHTML = '✓ ¡Lead registrado!';
          btn.style.backgroundColor = '#10b981';
          setTimeout(function() {{
            document.getElementById('contactModal').style.display='none';
            btn.innerHTML = original;
            btn.disabled = false;
            btn.style.backgroundColor = '';
            form.reset();
          }}, 2000);
        }} else {{
          if(window.gtag) gtag("event", "submit_error"); throw new Error("Error CRM");
        }}
      }} catch(error) {{
        btn.innerHTML = 'Fallo en CRM. Reintentar.';
        setTimeout(function() {{
          btn.innerHTML = original;
          btn.disabled = false;
        }}, 2000);
      }}
      return false;
    }}}}
  </script>

  <script>
    window.addEventListener('resize', function() {{
      if (window.chartRIN_instance) window.chartRIN_instance.resize();
      if (window.chartBalanza_instance) window.chartBalanza_instance.resize();
    }});
  </script>
</body>
</html>
"""
